name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  contents: read

env:
  EXTRA_SUBSTITUTERS: https://nix-community.cachix.org
  EXTRA_TRUSTED_PUBLIC_KEYS: nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  light-check:
    name: Light check
    runs-on: ubuntu-latest

    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.5
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-substituters = ${{ env.EXTRA_SUBSTITUTERS }}
            extra-trusted-public-keys = ${{ env.EXTRA_TRUSTED_PUBLIC_KEYS }}
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Check flake
        shell: bash
        run: |
          set -euo pipefail
          nix flake check -L

  full-build-and-cache:
    name: Full build and push cache
    runs-on: ubuntu-latest
    environment: default
    needs: light-check

    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name == github.repository &&
        github.event.pull_request.head.ref == 'update-flake-lock'
      )

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.5
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-substituters = ${{ env.EXTRA_SUBSTITUTERS }}
            extra-trusted-public-keys = ${{ env.EXTRA_TRUSTED_PUBLIC_KEYS }}
            experimental-features = nix-command flakes
            accept-flake-config = true
            keep-outputs = true
            keep-derivations = true
            trusted-users = root runner

      - name: Full build with nix-fast-build and push to Attic
        shell: bash
        env:
          ATTIC_ENDPOINT: ${{ vars.ATTIC_ENDPOINT }}
          ATTIC_CACHE: ${{ vars.ATTIC_CACHE }}
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
        run: |
          set -euo pipefail
          nix develop .#ci -c attic-init
          nix develop .#ci -c build-and-push

